server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/

turbine:
  aggregator:
    clusterConfig: SYSTEM
  appConfig: zuul-app-sample

spring:
  application:
    name: zuul-gw-turbine

