server:
  port: 8888

zuul:
  routes:
    zuul-app-sample:
      path: /users/
      serviceId: zuul-app-sample

ribbon:
  eureka:
    enabled: false

client:
  ribbon:
    listOfServers: 127.0.0.1:8080, 127.0.0.1:8081
