server:
  port: 8761

zuul:
  routes:
    zuul-service-sample:
      path: /users/**
      serviceId: zuul-service-sample
      stripPrefix: false

zuul-service-sample:
  ribbon:
    listOfServers: 127.0.0.1:9090

ribbon:
  eureka:
    enabled: false

eureka:
  instance:
    hostname: localhost
    secure-port-enabled: true
    non-secure-port-enabled: true
    lease-renewal-interval-in-seconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/

spring:
  application:
    name: zuul-gw-webapp


